# configuration.yml file

# identify the data source
data_source postgresdb:
  type: postgres
  connection:
    host: localhost
    username: postgres
    password: admin
  database: binar_bi
  schema: w3s_sample